version: '2'
services:
    jsense-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jsense/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jsense
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
